version: "3"
services:
  app:
    image: openjdk:16
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes: 
      - "./build/libs/needwork-0.0.1-SNAPSHOT.jar:/tmp/needwork.jar"
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /tmp/needwork.jar"
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pg"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"
      - "./docker/db/initdb:/docker-entrypoint-initdb.d"